### ISSUE TITLE
/Users/kavinvalli/.local/share/gh/extensions/gh-user-status/gh-user-status: line 54: /Users/kavinvalli/.local/share/gh/extensions/gh-user-status/bin/cmd.out: No such file or directory

### ISSUE THREAD

**Issue by kavinvalli** [vilmibm/gh-user-status#2]
![Screenshot 2021-08-27 at 8 26 47 PM](https://user-images.githubusercontent.com/41034356/131147443-695d768c-2f32-4b73-ac7b-7d3cd8a62423.png)

**Comment by vilmibm** [comment]
does this persist even after removing and reinstalling?

**Comment by hoyangtsai** [comment]
+1
Already upgraded `gh extension upgrade vilmibm/gh-user-status`

**Comment by kavinvalli** [comment]
@vilmibm @hoyangtsai I tried
1. Upgrading the extension - Didn't work
2. Removing the extension and then reinstalling it - Also didn't work

In case you need this, I'm using an M1 Macbook Air 2020

**Comment by andypiper** [comment]
Just hit the same issue here, and also tried removing and reinstalling. This is an M1 Pro MacBook Pro.

**Comment by vilmibm** [comment]
this should hopefully be fixed as of v1.1.0
